<?php

$rows_mails = "INSERT INTO `mails` (`type`,`subject`,`text`,`html`) VALUES
('activation_request','Validation d\'inscription','Bonjour et bienvenue sur le LORD.\n\nVotre inscription sur le lord est presque terminée, il ne vous reste plus qu\'à valider votre adresse e-mail en vous rendant au lien présent ci dessous.\n\n[link-to-replace]\n\nCe lien sera actif durant 48h, dépassé ce delais vous devrez redemander un nouvel envoi d\'email.','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px;margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Bonjour et bienvenue sur le LORD.</h3><p>Votre inscription sur le lord est presque terminée, il ne vous reste plus qu\'à valider votre adresse e-mail en cliquant sur le lien ci dessous.</p><p><a href=\'[link-to-replace]\'>[link-to-replace]</a></p><p>Ce lien sera actif durant 48h, dépassé ce delais vous devrez redemander un nouvel envoi d\'email.</p></body></html>'),
('activation_validated','Inscription Validée','Bonjour et bienvenue sur le LORD.\n\nBonjour [username]\nVous êtes désormais inscrits sur le LORD et votre compte est actif.\n\nIdentifiant : [email-adress]\nMot de passe : Connu de vous seul\n\nVous pourez vous connecter en vous rendant sur le lien ci dessous\n\n[link-to-replace]\n\nSi vous perdez votre mot de passe vous pourrez toujours le trouver en cherchant un peu dans votre tête.','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px;margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Bonjour et bienvenue sur le LORD.</h3><p>Bonjour <strong>Utilisateur</strong><br />Vous êtes désormais inscrits sur le LORD et votre compte est actif.<br /></p><ul><li>Identifiant : <strong>mail@mail.fr</strong></li><li>Mot de passe : <strong>Connu de vous seul</strong></li></ul><p>Vous pourez vous connecter en vous rendant sur le lien ci dessous.</p><p><a href=\'http://lord-rat.dev.kerwyn.fr/front/index.php?page=article&amp;load=connexion\'>Se Connecter</a></p><p>Si vous perdez votre mot de passe vous pourrez toujours le trouver en cherchant un peu dans votre tête.</p></body></html>'),
('request_reset_password','Demande de changement de mot de passe','Procédure de récupération de mot de passe\n\nSi vous recevez cet e-mail c\'est que vous avez perdu votre mot de passe.\nSi vous n\'êtes pas a l\'origine de cet e-mail vous pouvez tous simplement l\'ignorer et rien ne sera changé.\nSi vous êtes à l\'origine de ce message nous ne pouvons pas réccupérer votre mot de passe car celui ci est crypté.\nVous pouvez néanmoins en générer un nouveau en cliquant sur le lien suivant.\n\n[link-to-replace]','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px; margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Procédure de récupération de mot de passe</h3><p>Si vous recevez cet e-mail c\'est que vous avez perdu votre mot de passe.<br />Si vous n\'êtes pas a l\'origine de cet e-mail vous pouvez tous simplement l\'ignorer et rien ne sera changé.<br />Si vous êtes à l\'origine de ce message nous ne pouvons pas réccupérer votre mot de passe car celui ci est sécurisé.<br />Vous pouvez néanmoins en générer un nouveau en cliquant sur le lien suivant.</p><a href=\'[link-to-replace]\'>[link-to-replace]</a></body></html>'),
('reset_password_validated','Mot de passe changé avec succès','Procédure de récupération de mot de passe\n\nVotre mot de passe a été correctement changé. Merci de ne plus faire chier et de le retenir cette fois. ','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px;margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Procédure de récupération de mot de passe</h3><p>Votre mot de passe a été correctement changé. Merci de ne plus faire chier et de le retenir cette fois.</p></body></html>'),
('request_change_mail_old','Modification des informations de contact','Procédure de récupération de mot de passe\n\nVous recevez cet e-mail car une demande de changement d\'adresse mail à été réalisée. Vous pouvez anuler cette demande en cliquant sur le lien ci dessous.\n\n[link-to-replace]','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px;margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Procédure de récupération de mot de passe</h3><p>Vous recevez cet e-mail car une demande de changement d\'adresse mail à été réalisée.Vous pouvez anuler cette demande en cliquant sur le lien ci dessous.</p><a href=\'[link-to-replace]\'>[link-to-replace]</a></body></html>'),
('request_change_mail_new','Modification des informations de contact','Procédure de changement d\'adresse mail\n\nBonjour, vous avez demandé un changement d\'adresse mail. Pour ce faire merci de cliquer sur le lien ci dessous afin de valider la nouvelle adresse mail.[link-to-replace]','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px;margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Procédure de changement d\'adresse mail</h3><p>Bonjour, vous avez demandé un changement d\'adresse mail.Pour ce faire merci de cliquer sur le lien ci dessous afin de valider la nouvelle adresse mail.</p><a href=\'[link-to-replace]\'>[link-to-replace]</a></body></html>'),
('change_mail_old_validated','Modification des informations de contact','Procédure de récupération de mot de passe\n\nVous recevez cet e-mail car la demande de changement d\'adresse mail est désormais terminée.\nSi vous n\'avez pas fait cette demande de changement merci de contacter rapidement le staff en leurs communiquants le code suivant identifiant de transaction ','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px;margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Procédure de récupération de mot de passe</h3><p>Vous recevez cet e-mail car la demande de changement d\'adresse mail est désormais terminée.<br />Si vous n\'avez pas fait cette demande de changement merci de contacter rapidement le staff en leurs communiquants le code suivant <strong>identifiant de transaction</strong></p></body></html>'),
('change_mail_new_validated','Modification des informations de contact','Procédure de récupération de mot de passe\n\nLa nouvelle adresse mail à bien été validée sur le LORD.','<html><head><style type=\'text/css\'>html{background-color: #babebc;}body{font-family: Verdana, Arial, Helvetica, sans-serif;width: 700px;font-size: 0.90em;margin-left: auto;margin-right: auto;margin-top: 5px;margin-bottom: 5px;padding: 15px;color: black;border: solid 1px #955b44;background-color: white;}h3{color: #7b5239;text-align: center;}</style></head><body><h3>Procédure de récupération de mot de passe</h3><p>La nouvelle adresse mail à bien été validée sur le LORD.</p></body></html>')";

$rows_users = "INSERT INTO `users` VALUES
('','4497','kerwyn@live.fr','630e6e68f292c5a8dbba4d37204b2da6',NULL,'Kerwyn Raczaron','admin','0','0','0','0')";

$rows_users_civilites = "INSERT INTO `users_civilites` VALUES
(1, 'Monsieur', 'M'),(2, 'Madame', 'Mme'),(3, 'Mademoiselle', 'Mlle')";

$rows_antispam = "INSERT INTO `antispam` (`id`, `calcul`, `result`) VALUES
(1, '8 plus 5', 13),(2, '13 plus 5', 18),(3, '30 plus 4', 34),(4, '30 moins 10', 20),
(5, '21 plus 9', 30),(6, '26 moins 5', 21),(7, '2 fois 5', 10),(8, '3 fois 2', 6),
(9, '3 fois 5', 15),(10, '8 plus 12', 20),(11, '1 plus 2', 3),(12, '12 plus 2', 14),
(13, '13 moins 3', 10),(14, '49 moins 39', 10),(15, '26 plus 5', 31),(16, '4 fois 2', 8)
,(17, '2 fois 6', 12),(18, '5 plus 5', 10),(19, '6 plus 6', 12),(20, '1 plus 50', 51),
(21, '20 fois 1', 20),(22, '50 moins 15', 35),(23, '12 plus 12', 24),(24, '15 plus 10', 25),
(25, '13 plus 17', 30),(26, '15 plus 16', 31),(27, '20 moins 5', 15),(28, '12 moins 2', 10),
(29, '12 moins 5', 7),(30, '8 plus 8 moins 6', 10),(31, '5 plus 5 plus 5', 15),
(32, '2 fois 2 fois 2', 8),(33, '6 plus 16', 22),(34, '3 fois 3', 9),(35, '5 plus 5', 10),
(36, '10 moins 4', 6),(37, '50 moins 1', 49),(38, '51 plus 4', 55),(39, '60 moins 35', 25),
(40, '12 plus 6 plus 2', 20),(41, '1 plus 1', 2),(42, '2 plus 1', 3),(43, '3 plus 2', 5),
(44, '5 plus 3', 8),(45, '8 plus 5', 13),(46, '13 plus 8', 21),(47, '21 plus 13', 34),
(48, '34 moins 8', 26),(49, '26 mons 8', 18),(50, '18 moins 6', 12),(51, '12 moins 4', 8),
(52, '10 plus 5', 15),(53, '15 plus 10', 25),(54, '25 plus 15', 40),(55, '40 plus 25', 65),
(56, '65 moins 10', 55),(57, '55 moins 5', 50),(58, '20 fois 2', 40),(59, '50 moins 20', 30),
(60, '50 moins 30', 20);";

$rows_langues = "INSERT INTO `langues` VALUES
(1, 'France', 'actif');";
